version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/subscription_db"
      JWT_SECRET: "your-super-secret-jwt-key"
      FRONTEND_URL: "http://localhost:5173"
    depends_on:
      - postgres
    volumes:
      - /mnt/data:/mnt/data:ro

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: